version: '3'

services:
  hotel:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "hotel"
    ports:
      - "15432:5432"
    volumes:
      - $HOME/volumes:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  hotel-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "hotel@hotel.com"
      PGADMIN_DEFAULT_PASSWORD: "hotel"
    ports:
      - "16543:80"
    depends_on:
      - hotel
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
